config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    devise_for :users
    root "static_pages#index"
    get "static_pages/about"
    get "static_pages/help"
    as :user do
      post "signin" => "devise/sessions#create"
      delete "signout" => "devise/sessions#destroy"
    end
    resources :users do
      collection do
        get :signin
        get :signup
      end
    end
    resources :events do
      resources :tasks
    end

    namespace :admin do
      root "admins#index"
      resources :events
      resources :users
      resources :stories
      resources :topics do
        resources :tasks
      end
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  include PublicActivity::Model
  tracked owner: Proc.new { |controller, model| controller.current_user ? controller.current_user : nil }


  belongs_to :user
  belongs_to :topic, optional: true
  has_many :tasks, dependent: :destroy

  enum status: {open: 0, in_progress: 1, pending: 2, completed: 3}

  before_save :add_tasks_with_topic, if: -> {topic}

  private

  def add_tasks_with_topic
    tasks_topic = self.topic.tasks.where(parent_id: nil)
    @tasks_event = []
    tasks_topic.each do |task|
      task_dup = task.dup
      task_dup.event_id = id
      task_dup.topic_id = nil
      task_dup.start_time = Time.now
      task_dup.save
      @tasks_event << task_dup
      dup_sub_tasks task, task_dup.id
    end if changes.has_key?(:topic_id)
    self.tasks << @tasks_event
  end

  def dup_sub_tasks task, task_dup_id
    task.sub_tasks.each do |task|
      task_dup = task.dup
      task_dup.event_id = id
      task_dup.topic_id = nil
      task_dup.start_time = Time.now
      task_dup.parent_id = task_dup_id
      task_dup.save
      @tasks_event << task_dup
      dup_sub_tasks task, task_dup.id
    end
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::AdminsController
  load_and_authorize_resource

  def index
    @q = Event.ransack(params[:q])
    @events = @q.result.page(params[:page]).per(params[:per_page] || Settings.per_page)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource
  before_action :load_event, only: %i(show edit update destroy)

  def index
    @events = current_user.events.order(happen_at: :desc)
  end

  def show
    @q = @event.tasks.ransack(params[:q])
    @tasks = @q.result.page(params[:page]).per(params[:per_page] || Settings.per_page)
    @data_chart = Statistic::BuildDataStatisticService.new(@event, @event.tasks).perform
    gon.id_json = @event.id
    gon.event_id = @event.id
    gon.url_new_task = new_event_task_path event_id: @event.id
  end

  def new; end

  def edit; end

  def update
    respond_to do |format|
      if @event.update event_params
        format.html{redirect_to (current_user.admin? ? admin_events_path : event_url(@event)), success: "Cập nhật thông tin sự kiện thành công"}
        format.json{render :show, status: :ok, location: @event}
      else
        flash.now[:error] = @event.errors.full_messages.to_sentence
        format.js
      end
    end
  end

  def create
    @event = current_user.events.new event_params
    @event.user = current_user unless @event.user
    if @event.save
      flash[:success] = "Tạo sự kiện thành công"
      redirect_to (current_user.admin? ? admin_events_path : event_url(@event))
    else
      flash.now[:error] = @event.errors.full_messages.to_sentence
    end
  end

  def destroy
    @event.destroy
    flash[:success] = "Xóa sự kiện thành công"
    redirect_to (current_user.admin? ? admin_events_path : root_path)
  end

  private

  def event_params
    params.require(:event).permit :name, :description, :happen_at, :location, :status, :topic_id, :user_id
  end

  def load_event
    @event = current_user.events.find_by id: params[:id]
    @event = Event.find_by id: params[:id] if current_user.admin?

    return if @event

    flash[:warning] = "Event khong ton tai"
    redirect_to root_path
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_event.html.erb
<tr>
  <th scope="row"><%= link_to event.id, event_path(event), class: "text-decoration-none text-primary fw-bold" %></th>
  <td><%= link_to event.user_id.to_s + "_" + event.user.last_name, admin_user_path(event.user_id), class: "text-decoration-none text-primary fw-bold" %></td>
  <td><%= event.name %></td>
  <td><%= event.tasks.any? ? (event.tasks.sum(:progress) / event.tasks.count).round(3) : 0 %></td>
  <td><%= event.tasks.size %></td>
  <td><%= event.topic&.name || "None" %></td>
  <td><%= event.location %></td>
  <td><%= event.happen_at.strftime "%H:%M %d-%m-%Y" %></td>
  <td><%= parse_time event.created_at %></td>
  <td>
    <%= link_to event_path(event), class: "text-decoration-none text-success fw-bold me-2" do %>
      <i class="fa-solid fa-eye"></i>
    <% end %>
    <%= link_to edit_admin_event_path(event), remote: true, class: "text-decoration-none text-primary fw-bold mx-2" do %>
      <i class="fa-solid fa-pen-to-square"></i>
    <% end %>
    <%= content_tag :span, onclick: "confirm_delete('#{event_path event}')",
      class: "text-decoration-none text-danger fw-bold mx-2" do %>
      <i class="fa-solid fa-trash-can"></i>
    <% end %>
  </td>
</tr>

app/views/admin/events/index.html.erb
<% provide :title, "Collections event" %>
<div class="mb-4 row">
  <h2 class="col-8">
    Collections event
  </h2>
  <div class="col">
    <div class="float-end">
      <%= link_to "Create topic", new_admin_event_path,
        class:"btn btn-primary mx-3", remote: true %>
    </div>
  </div>
</div>
<div class="my-3 overflow-auto">
  <table class="table table-striped table-hover shadow border">
    <thead>
      <tr>
        <th scope="col"><%= sort_link @q, :id, "#ID",class: "text-decoration-none" %></th>
        <th scope="col"><%= sort_link @q, :user_id, class: "text-decoration-none" %></th>
        <th scope="col"><%= sort_link @q, :name, "Event name", class: "text-decoration-none" %></th>
        <th scope="col"><%= sort_link @q, :progress, class: "text-decoration-none" %></th>
        <th scope="col">Number of tasks</th>
        <th scope="col"><%= sort_link @q, :topic_name, "Topic", class: "text-decoration-none" %></th>
        <th scope="col"><%= sort_link @q, :location, class: "text-decoration-none" %></th>
        <th scope="col"><%= sort_link @q, :happen_at, class: "text-decoration-none" %></th>
        <th scope="col"><%= sort_link @q, :created_at, class: "text-decoration-none" %></th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <%= render @events %>
    </tbody>
  </table>
</div>