config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    devise_for :users
    root "static_pages#index"
    get "static_pages/about"
    get "static_pages/help"
    as :user do
      post "signin" => "devise/sessions#create"
      delete "signout" => "devise/sessions#destroy"
    end
    resources :users do
      collection do
        get :signin
        get :signup
      end
    end
    resources :events do
      resources :tasks
    end

    namespace :admin do
      root "admins#index"
      resources :events
      resources :users
      resources :stories
      resources :topics do
        resources :tasks
      end
    end
  end
end

app/views/layouts/admin/_top_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark navbar-light" style="background-color: #203239;"">
  <div class="container-fluid">
    <%= link_to "S-event", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Admin Dashboard", admin_root_path,
            class:"nav-link #{"active fw-bold" if controller.controller_name.to_sym == :admins }", "aria-current": "page" %>
        </li>
        <li class="nav-item">
          <li>
            <%= link_to t("navbar.events"), admin_events_path,
              class: "nav-link #{"active fw-bold" if controller.controller_name.to_sym == :events }" %>
          </li>
        </li>
        <li class="nav-item">
          <%= link_to t("navbar.topics"), admin_topics_path,
            class: "nav-link #{"active fw-bold" if controller.controller_name.to_sym == :topics }" %>
        </li>
        <li class="nav-item">
          <%= link_to t("navbar.users"), admin_users_path,
            class: "nav-link #{"active fw-bold" if controller.controller_name.to_sym == :users }" %>
        </li>
        <li class="nav-item">
          <%= link_to t("navbar.activity"), admin_stories_path,
            class: "nav-link #{"active fw-bold" if controller.controller_name.to_sym == :stories }" %>
        </li>
        <%= render "layouts/dropdown" %>
      </ul>
      <%= search_form_for @q, url: root_path,
        class: "d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" do |f| %>
        <div class="input-group">
          <%= f.search_field :name_or_description_cont, class: "form-control bg-light border-0 small",
            placeholder: t("navbar.search_event") %>
          <%= button_tag(type: :submit, class: 'btn btn-primary') do %>
            <i class="fas fa-search fa-sm"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= render "layouts/shim" %>
    <%= include_gon %>
  </head>
  <body>
    <%= render "layouts/admin/top_bar" %>
    <div class="container-fluid bg-light p-5 min-vh-100">
      <%= yield %>
    </div>
  </body>
  <%= render (user_signed_in? ? "layouts/footer" : "layouts/footer_landing_page") %>
  <%= render "layouts/modal" %>
  <%= render "layouts/modal_small" %>
  <div id="flash">
    <%= render "layouts/flash_toast" %>
  </div>
</html>
<%= javascript_pack_tag "components/init_functions.js" %>
<%= javascript_pack_tag "components/init_variables.js" %>