config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    devise_for :users
    root "static_pages#index"
    get "static_pages/about"
    get "static_pages/help"
    as :user do
      post "signin" => "devise/sessions#create"
      delete "signout" => "devise/sessions#destroy"
    end
    resources :users do
      collection do
        get :signin
        get :signup
      end
    end
    resources :events do
      resources :tasks
    end

    namespace :admin do
      root "admins#index"
      resources :events
      resources :users
      resources :stories
      resources :topics do
        resources :tasks
      end
    end
  end
end

app/views/shared/_activities.html.erb
<div class="col-sm-3">
  <%= render_activities @activities %>
</div>

app/views/shared/_landing_page.html.erb
<div>
  <section class="fixed-top navigation fs-5">
    <nav class="container row justify-content-between navbar navbar-expand-lg navbar-light">
      <div class="fs-1 fw-bold ms-5 col-3">
        <%= image_tag "s-event-logo.png", style:"width: 45px" %>
        <%= link_to "S-event", root_path, class: "navbar-brand text-logo" %>
      </div>
      <div class="collapse navbar-collapse text-center" id="navbar">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Home", root_path(anchor: :home),
              class: "nav-link #{"active" if controller_name.to_sym == :static_pages}", "aria-current": "page" %>
          </li>
          <li class="nav-item">
            <%= link_to "About", root_path(anchor: :about_us), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Connect", root_path(anchor: :footer), class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Forgot your password?", new_password_path(resource_name),
              class: "nav-link #{"active" if controller_name.to_sym == :passwords }" %>
          </li>
          <li class="nav-item">
            <%= link_to "Account Verification", new_confirmation_path(resource_name),
              class: "nav-link #{"active" if controller_name.to_sym == :confirmations }" %>
          </li>
        </ul>
      </div>
    </nav>
  </section>
  <section id="home">
    <div class="col-12 min-vh-100 p-5 bg-page mb-5" style="background-image: url(<%= asset_path "banner-bg.png" %>)">
      <div class="container p-5">
        <div class="row">
          <div class="row col-lg-12 text-center">
            <h1 class="mb-3">
              Take Control of your
              <br>
              Event
            </h1>
            <p class="mb-4">
              Mark your life with the most wonderful events.
              <br>
              S-event always supports you
            </p>
            <div class="row justify-content-center">
            <%= link_to "Sign in", signin_users_path, remote: true,
              class: "btn-grad text-light fw-bold btn px-5 py-2 fs-6 btn-lg mb-5 col-2" %>
            <%= link_to "Sign up", signup_users_path, remote: true,
              class: "btn-grad text-light fw-bold btn px-5 py-2 fs-6 btn-lg mb-5 col-2" %>
            </div>
            <%= image_tag "banner.png", class: "img-fluid col-12" %>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="section feature my-5" id="about_us">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center my-5">
          <h2 class="section-title">Awesome Features</h2>
        </div>
        <div class="col-md-6 mb-5">
          <div class="d-flex feature-item shadow p-3 rounded-3">
            <div>
              <h4>Tạo lịch trình</h4>
              <p>Hỗ trợ tạo lịch trình và quản lý sự kiện</p>
            </div>
          </div>
        </div>
        <div class="col-md-6 mb-80">
          <div class="d-flex feature-item shadow p-3 rounded-3">
            <div>
              <h4>Chủ đề </h4>
              <p>Đa dạng với nhiều chủ đề sự kiện và sự kiện khácc nhau</p>
            </div>
          </div>
        </div>
        <div class="col-md-6 mb-80">
          <div class="d-flex feature-item shadow p-3 rounded-3">
            <div>
              <h4>Lịch trình</h4>
              <p>Lịch trình công việc trực quan</p>
            </div>
          </div>
        </div>
        <div class="col-md-6 mb-80">
          <div class="d-flex feature-item shadow p-3 rounded-3">
            <div>
              <h4>Thống kê</h4>
              <p>Báo cáo thống kê chi tiết</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
<script>
  if ($('.navigation').offset().top > 10) {
    $('.navigation').addClass('nav-bg');
  } else {
    $('.navigation').removeClass('nav-bg');
  }
  $(window).scroll(function () {
    if ($('.navigation').offset().top > 10) {
      $('.navigation').addClass('nav-bg');
    } else {
      $('.navigation').removeClass('nav-bg');
    }
  });
</script>

app/views/shared/_login.html.erb
<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="mb-3">
    <%= f.label :email, class: "form-label" %>
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control", placeholder: "Email address" %>
  </div>
  <div class="mb-3">
    <%= f.label :password, class: "form-label" %>
    <%= f.password_field :password, autocomplete: "current-password", class: "form-control", placeholder: "Password" %>
  </div>
  <% if devise_mapping.rememberable? %>
    <div class="mb-3 form-check">
      <%= f.check_box :remember_me, class: "form-check-input"%>
      <%= f.label :remember_me, class: "form-check-label" %>
    </div>
  <% end %>
  <%= f.submit "Sign in", class: "btn btn-primary" %>
  <div class="">
    <%= render "devise/shared/links" %>
  </div>
<% end %>

app/views/shared/_progress.html.erb
<div class="progress">
  <div class="progress-bar progress-bar-striped progress-bar-animated <%= color_completion_rate task.progress %>" role="progressbar" 
    style="width: <%= task.progress || 0 %>%;" 
    aria-valuenow="<%= task.progress || 0 %>" 
    aria-valuemin="0" aria-valuemax="100">
    <%= task.progress || 0 %>%
  </div>
</div>

app/views/shared/_signup.html.erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name), class: "mt-8 space-y-6") do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>
  <div class="mb-3">
    <%= f.label :email, class: "form-label" %>
    <%= f.email_field :email, autofocus: true, autocomplete: "email",
      class: "form-control", placeholder: "Email address" %>
  </div>
  <div class="mb-3">
    <%= f.label :password, class: "form-label" %>
    <%= f.password_field :password, autocomplete: "new-password",
      class: "form-control", placeholder: "Password" %>
  </div>
  <div class="mb-3">
    <%= f.label :password_confirmation, class: "form-label" %>
    <%= f.password_field :password_confirmation, autocomplete: "new-password",
      class: "form-control", placeholder: :password_confirmation %>
  </div>
  <%= f.submit "Sign up", class: "btn btn-primary" %>
  <div class="">
    <%= render "devise/shared/links" %>
  </div>
<% end %>