config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    devise_for :users
    root "static_pages#index"
    get "static_pages/about"
    get "static_pages/help"
    as :user do
      post "signin" => "devise/sessions#create"
      delete "signout" => "devise/sessions#destroy"
    end
    resources :users do
      collection do
        get :signin
        get :signup
      end
    end
    resources :events do
      resources :tasks
    end

    namespace :admin do
      root "admins#index"
      resources :events
      resources :users
      resources :stories
      resources :topics do
        resources :tasks
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attr_accessor :verification
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable, :timeoutable

  has_many :events, dependent: :destroy
  has_many :tasks, through: :events

  enum role: {customer: 0, admin: 1, staff: 2}
  enum gender: {male: 0, female: 1, other: 2}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  VALID_PHONE_REGEX = /\d[0-9]\)*\z/.freeze
  validates :first_name, presence: true,
    length: {maximum: Settings.validation.max_length_50}
  validates :last_name, presence: true,
    length: {maximum: Settings.validation.max_length_50}, allow_blank: false
  validates :phone, presence: true,
    format: {with: VALID_PHONE_REGEX}, allow_blank: true
  validates :email, presence: true,
    length: {maximum: Settings.validation.max_length_255},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: true
  validates :password, presence: true, length:
    {minimum: Settings.validation.min_length_6}, allow_nil: true
  before_save{email.downcase!}

  def full_name
    first_name + " " + last_name
  end

  def online?
    updated_at > 1.minute.ago
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminsController
  load_and_authorize_resource

  def index
    @q_user = User.ransack(params[:q])
    @users = @q_user.result.page(params[:page]).per(params[:per_page] || Settings.per_page)
  end

  def show
    @activities = PublicActivity::Activity.where(owner: params[:id]).page(params[:page]).per(params[:per_page] || Settings.per_page_10)
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "Tạo user thành công"
      redirect_to admin_users_path
    else
      flash.now[:error] = @user.errors.full_messages.to_sentence
    end
  end

  def update
    user_params_changed = user_params
    if user_params[:password].blank? && user_params[:password_confirmation].blank?
      user_params_changed.delete(:password)
      user_params_changed.delete(:password_confirmation)
    end
    if ActiveModel::Type::Boolean.new.cast(user_params[:verification])
      user_params_changed[:confirmed_at] = Time.now unless @user.confirmed_at
    else
      user_params_changed[:confirmed_at] = nil
    end
    respond_to do |format|
      if @user.update user_params_changed
        format.html{redirect_to admin_users_path, success: "Cập nhật thông tin topic thành công"}
      else
        flash.now[:error] = @user.errors.full_messages.to_sentence
        format.js
      end
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "Xóa User thành công"
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit :first_name, :last_name, :email, :date_of_birth, :phone,
      :address, :gender, :password, :password_confirmation, :verification
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: [:show]

  skip_before_action :authenticate_user!, except: %(show)


  def show; end

  def signin
  end

  def signup
  end

  private
  def load_user
    @user = User.find_by id: params[:id]
    return if @user

    flash[:danger] = t "users.nil"
    redirect_to root_path
  end
end

app/views/admin/users/_event.html.erb
<%= link_to event_path(event), class: "list-group-item list-group-item-action" do %>
  <div class="d-flex w-100 justify-content-between">
    <h4 class="mb-1"><%= event.name %></h4>
    <small class="text-muted"><%= time_ago_in_words event.created_at %></small>
  </div>
  <p class="mb-1"><%=h truncate(event.description, length: 200) %></p>
  <div class="d-flex w-100 justify-content-between my-2">
    <small class="text-muted fw-bold">
      Topic
      &nbsp;/&nbsp;
      <%= event.topic&.name || "None"%>
    </small>
    <small class="text-muted fw-bold">
      Location
      &nbsp;/&nbsp;
      <%= event.location %>
    </small>
    <small class="text-muted fw-bold">
      Happen at
      &nbsp;/&nbsp;
      <%= parse_time event.happen_at %>
    </small>
    <small class="text-muted fw-bold">
      Status
      &nbsp;/&nbsp;
      <span class="badge rounded-pill <%= status_color event.status %>">
        <%= event.status.capitalize %>
      </span>
    </small>
  </div>
<% end %>

app/views/admin/users/_events_user.html.erb
<div class="bg-white shadow my-5 rounded-3 border-start-5 border-left-info">
  <div class="list-group">
    <% @user.events.each do |event|%>
      <%= render "admin/users/event", event: event %>
    <% end %>
  </div>
</div>

app/views/admin/users/_info_user.html.erb
<div class="row align-items-center">
  <div class="col-lg-5 row justify-content-evenly">
    <%= image_tag "avatar_none.webp", class: "col-8" %>
  </div>
  <div class="col-lg-6">
    <div class="about-text go-to">
      <h3 class="dark-color"><%= @user.full_name %></h3>
      <div class="row about-list my-3">
        <div class="col-md-6">
          <div class="media my-3">
            <label class="fw-bold">Birthday</label>&nbsp;/&nbsp;
            <%= @user.date_of_birth %>
          </div>
          <div class="media my-3">
            <label class="fw-bold">Address</label>&nbsp;/&nbsp;
            <%= @user.address %>
          </div>
          <div class="media my-3">
            <label class="fw-bold">Gender</label>&nbsp;/&nbsp;
            <%= @user.gender %>
          </div>
          <div class="media my-3">
            <label class="fw-bold">Phone</label>&nbsp;/&nbsp;
            <%= @user.phone %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="media my-3">
            <label class="fw-bold">Email</label>&nbsp;/&nbsp;
            <%= @user.email %>
          </div>
          <div class="media my-3">
            <label class="fw-bold">Account type</label>&nbsp;/&nbsp;
            <%= @user.role %>
          </div>
          <div class="media my-3">
            <label class="fw-bold">Last sign in</label>&nbsp;/&nbsp;
            <%= time_ago_in_words @user.last_sign_in_at if @user.last_sign_in_at %>
          </div>
          <div class="media my-3">
            <label class="fw-bold">Created at</label>&nbsp;/&nbsp;
            <%= parse_time @user.created_at %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/_statistic_user.html.erb
<div class="bg-white shadow p-3 my-3 rounded-3 border-start-5 border-left-success position-relative">
  <div class="row">
    <div class="col-6 col-lg-3">
      <div class="count-data text-center text-success fw-bold">
        <h6 class="count h2" data-to="500" data-speed="500"><%= @user.events.size %></h6>
        <p class="m-0px text-opacity-75">Events</p>
      </div>
    </div>
    <div class="col-6 col-lg-3">
      <div class="count-data text-center text-success fw-bold">
        <h6 class="count h2" data-to="150" data-speed="150"><%= @user.tasks.size %></h6>
        <p class="m-0px text-opacity-75">Tasks</p>
      </div>
    </div>
    <div class="col-6 col-lg-3">
      <div class="count-data text-center text-success fw-bold">
        <h6 class="count h2" data-to="150" data-speed="150"><%= @user.tasks.completed.size %></h6>
        <p class="m-0px text-opacity-75">Tasks Completed</p>
      </div>
    </div>
    <div class="col-6 col-lg-3">
      <div class="count-data text-center text-success fw-bold">
        <h6 class="count h2" data-to="190" data-speed="190"><%= number_to_currency(@user.tasks.sum(:actual_costs), locale: :vi) %></h6>
        <p class="text-opacity-75">Costs</p>
      </div>
    </div>
  </div>
  <span class="position-absolute top-0 start-100 translate-middle badge
    rounded-pill <%= @user.online? ? 'bg-success' : 'bg-secondary' %>">
    <%= @user.online? ? "Online" : "Offline" %>
  </span>
</div>

app/views/admin/users/_user.html.erb
<tr>
  <th scope="row"><%= link_to user.id, admin_user_path(user), class: "text-decoration-none text-primary fw-bold" %></th>
  <td><%= user.full_name %></td>
  <td><%= user.email %></td>
  <td><%= user.role %></td>
  <td>
    <% if user.online? %>
      <span class="badge bg-success">Online</span>
    <% else %>
      <span class="badge bg-secondary">Offline</span>
    <% end %>
  </td>
  <td>
    <% if user.confirmed_at %>
      <span class="badge bg-success">Confirmed</span>
    <% else %>
      <span class="badge bg-danger">Unconfimred</span>
    <% end %>
  </td>
  <td><%= time_ago_in_words user.last_sign_in_at if user.last_sign_in_at %></td>
  <td><%= parse_time user.created_at %></td>
  <td>
    <%= link_to admin_user_path(user), class: "text-decoration-none text-success fw-bold me-2" do %>
      <i class="fa-solid fa-eye"></i>
    <% end %>
    <%= link_to edit_admin_user_path(user), remote: true, class: "text-decoration-none text-primary fw-bold mx-2" do %>
      <i class="fa-solid fa-pen-to-square"></i>
    <% end %>
    <%= content_tag :span, onclick: "confirm_delete('#{admin_user_path user}')",
      class: "text-decoration-none text-danger fw-bold mx-2" do %>
      <i class="fa-solid fa-trash-can"></i>
    <% end %>
  </td>
</tr>

app/views/admin/users/create.js.erb
$('#flash').html('<%= j render "layouts/flash" %>')

app/views/admin/users/edit.html.erb
<div class="p-5 m-5">
  <h2>Chỉnh sửa user</h2>
  <%= render "admin/users/form", user: @user %>
</div>

app/views/admin/users/edit.js.erb
$('#exampleModalLabel').html('Chỉnh sửa task of topic')
$('#modal_body').html('<%= j render "admin/users/form", user: @user %>')
myModal.show();

app/views/admin/users/index.html.erb
<% provide :title, "Collections event" %>
<div class="mb-4 row">
  <h2 class="col-8">
    Collections event
  </h2>
  <div class="col">
    <div class="float-end">
      <%= link_to "Create user", new_admin_user_path,
        class:"btn btn-primary mx-3", remote: true %>
    </div>
  </div>
</div>
<div class="my-3 overflow-auto">
  <table class="table table-striped table-hover shadow border">
    <thead>
      <tr>
        <th scope="col"><%= sort_link @q_user, :id, "#ID",class: "text-decoration-none" %></th>
        <th scope="col"><%= sort_link @q_user, :name, class: "text-decoration-none" %></th>
        <th scope="col"><%= sort_link @q_user, :email, class: "text-decoration-none" %></th>
        <th scope="col"><%= sort_link @q_user, :role, class: "text-decoration-none" %></th>
        <th scope="col"><%= sort_link @q_user, :updated_at, "Status", class: "text-decoration-none" %></th>
        <th scope="col"><%= sort_link @q_user, :confirmed_at, "Confirmed",class: "text-decoration-none" %></th>
        <th scope="col"><%= sort_link @q_user, :last_sign_in_at, class: "text-decoration-none" %></th>
        <th scope="col"><%= sort_link @q_user, :created_at, class: "text-decoration-none" %></th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <%= render @users %>
    </tbody>
  </table>
</div>

app/views/admin/users/new.html.erb
<div class="p-5 m-5">
  <h2>Create new user</h2>
  <%= render "admin/users/form", user: @user %>
</div>

app/views/admin/users/new.js.erb
$('#exampleModalLabel').html('Create new user')
$('#modal_body').html('<%= j render "admin/users/form", user: @user %>')
myModal.show();

app/views/admin/users/show.html.erb
<section class="gray-bg">
  <div class="container">
    <%= render "admin/users/info_user" %>
    <%= render "admin/users/statistic_user" %>
    <%= render "admin/users/events_user" %>
    <div class="bg-white shadow my-5 rounded-3 border-start-5 border-left-danger">
      <div class="list-group">
        <div class="m-3">
          <%= page_entries_info @activities, entry_name: "Activities" %>
        </div>
        <%= render_activities(@activities) %>
        <div class="m-3">
          <%= paginate @activities %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/users/update.js.erb
$('#flash').html('<%= j render "layouts/flash" %>')